
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asj
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: auth-service

jwt:
  secret: auth_service_jwt_secret_change_in_prod_to_strong_secret_at_least_32_chars_long
  access-token-expiration-minutes: 120
  refresh-token-expiration-days: 30
